apiVersion: v1
kind: Service
metadata:
  name: conversao-api-service
spec:
  selector:
    app: conversao-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80  
  type: ClusterIP
